#!/bin/bash


bake_task build "Builds the game."
function build {
  docker build -f 'build/Dockerfile' -t 'pong:latest' .
}


bake_task compose "Runs docker compose."
function compose {
  docker-compose -f 'build/docker-compose.yml' "$@"
}


bake_task exec "Execs into the game server."
function exec {
  compose run server "$@"
}


bake_task yarn "Runs yarn in the container."
function yarn {
  compose run server yarn "$@"
}


bake_task run "Runs the game server."
function run {
  compose run --service-ports server yarn run:live
}


bake_task run:prod "Runs the production game server."
function run:prod {
  compose up
}
